name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ./MusicmarketApp/MusicMarketTests/MusicMarket.Tests.csproj
    - name: Build
      run: dotnet build ./MusicmarketApp/MusicMarketTests/MusicMarket.Tests.csproj --configuration Release --no-restore

    - name: Tests
      run: dotnet test ./MusicmarketApp/MusicMarketTests/MusicMarket.Tests.csproj --configuration Release --verbosity normal
